spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 127.0.0.1
    database: 0

server:
  port: 1111

mybatis:
  mapper-locations: classpath:mapper/*.xml





