server:
  port: 4444
spring:
  application:
    name: school-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
#      config:
#        server-addr: 127.0.0.1:8848
#        file-extension: yaml
#        shared-configs[0]:
#          dataId: gateway.yaml
#          refresh: true
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
      - id: school-server
        uri: lb://school-server
        predicates:
        - Path=/school/**
      - id: school-auth
        uri: lb://school-auth
        predicates:
        - Path=/auth/**,/oauth/**,/user/**


  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
