server:
  port: 4444
spring:
  application:
    name: school-gateway

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
      - id: school-server
        uri: lb://school-server
        predicates:
        - Path=/school/**
      - id: school-auth
        uri: lb://school-auth
        predicates:
        - Path=/auth/**
    nacos:
      discovery:
        server-addr: localhost:8848

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
